services:
  stats-server:
    build: stats-service/server
    image: server
    container_name: server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=explore-with-me
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345

  ewm-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=explore-with-me
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
